name: qrtools
description: a toolkit for qrcodes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.1.0
  qr_code_scanner: ^0.4.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.4
  qr_flutter: ^4.0.0
  path_provider: ^2.0.1
  wc_flutter_share: ^0.4.0
  permission_handler: ^8.0.0+1
  another_flushbar: ^1.10.22
  clipboard_manager: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
